// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpbdr1BQquXPsBzQaQGxA00nnTJZgmE-A',
    appId: '1:603638530965:web:d380ad4e4efe3916d8ec9c',
    messagingSenderId: '603638530965',
    projectId: 'mental-health-3aa73',
    authDomain: 'mental-health-3aa73.firebaseapp.com',
    storageBucket: 'mental-health-3aa73.firebasestorage.app',
    measurementId: 'G-M01292MWJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDun3_RVEqcTvl90Iz9nhKgPRatDwHkT-Q',
    appId: '1:603638530965:android:54de48b4f2567c50d8ec9c',
    messagingSenderId: '603638530965',
    projectId: 'mental-health-3aa73',
    storageBucket: 'mental-health-3aa73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWYfLOCqrpPJQbMQGMKefua9Dz9lzfPoQ',
    appId: '1:603638530965:ios:7aa436b91c2a265cd8ec9c',
    messagingSenderId: '603638530965',
    projectId: 'mental-health-3aa73',
    storageBucket: 'mental-health-3aa73.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWYfLOCqrpPJQbMQGMKefua9Dz9lzfPoQ',
    appId: '1:603638530965:ios:7aa436b91c2a265cd8ec9c',
    messagingSenderId: '603638530965',
    projectId: 'mental-health-3aa73',
    storageBucket: 'mental-health-3aa73.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpbdr1BQquXPsBzQaQGxA00nnTJZgmE-A',
    appId: '1:603638530965:web:ef65565e1f056922d8ec9c',
    messagingSenderId: '603638530965',
    projectId: 'mental-health-3aa73',
    authDomain: 'mental-health-3aa73.firebaseapp.com',
    storageBucket: 'mental-health-3aa73.firebasestorage.app',
    measurementId: 'G-5XF26SHK16',
  );
}
